CREATE TABLE tbl_cbt(
CBT_SEQ	NUMBER	NOT NULL	PRIMARY KEY,
CBT_SENTE	nVARCHAR2(125)	NOT NULL	,
CBT_FST	nVARCHAR2(70)	NOT NULL	,
CBT_SND	nVARCHAR2(70)	NOT NULL	,
CBT_TRD	nVARCHAR2(70)	NOT NULL	,
CBT_FTH	nVARCHAR2(70)	NOT NULL	,
CBT_NUM	NUMBER	NOT NULL	,
CBT_RIGHT	VARCHAR2(1)		
);

DROP TABLE tbl_cbt;

CREATE TABLE tbl_cbt(
CBT_SEQ	VARCHAR2(5)	NOT NULL	PRIMARY KEY,
CBT_QNO	VARCHAR2(5)	NOT NULL	,
CBT_SENTE	nVARCHAR2(125)	NOT NULL	,
CBT_RIGHT	VARCHAR2(1)		
);

CREATE TABLE tbl_qst(
QST_NUM	VARCHAR2(5)	NOT NULL	PRIMARY KEY,
QST_FST	nVARCHAR2(70)	NOT NULL	,
QST_SND	nVARCHAR2(70)	NOT NULL	,
QST_TRD	nVARCHAR2(70)	NOT NULL	,
QST_FTH	nVARCHAR2(70)	NOT NULL	,
SQT_NUM	NUMBER	NOT NULL	
);
DROP TABLE tbl_qst;

CREATE TABLE tbl_qst(
QST_NUM	VARCHAR2(5)	NOT NULL	PRIMARY KEY,
QST_FST	nVARCHAR2(70)	NOT NULL	,
QST_SND	nVARCHAR2(70)	NOT NULL	,
QST_TRD	nVARCHAR2(70)	NOT NULL	,
QST_RN	nVARCHAR2(70)	NOT NULL
);

DROP TABLE tbl_cbt;
DROP TABLE tbl_qst;

CREATE TABLE tbl_cbt(
CBT_SEQ	NUMBER	NOT NULL	PRIMARY KEY,
CBT_SENTE	nVARCHAR2(125)	NOT NULL	,
CBT_RIGHT	VARCHAR2(1)		,
CBT_FST	nVARCHAR2(70)	NOT NULL	,
CBT_SND	nVARCHAR2(70)	NOT NULL	,
CBT_TRD	nVARCHAR2(70)	NOT NULL	,
CBT_FTH	nVARCHAR2(70)	NOT NULL	,
CBT_RN	NUMBER	NOT NULL	,
CBT_PAST	VARCHAR2(1)		,
CBT_ORDER	NUMBER		
);

SELECT * FROM tbl_cbt;