CREATE TABLE tbl_rent_book(
RENT_SEQ	NUMBER	NOT NULL	PRIMARY KEY,
RENT_DATE	VARCHAR2(10)	NOT NULL	,
RENT_RETURN_DATE	VARCHAR2(10)	NOT NULL	,
RENT_BCODE	VARCHAR2(6)	NOT NULL	,
RENT_UCODE	VARCHAR2(6)	NOT NULL	,
RENT_RETUR_YN	VARCHAR2(1)		,
RENT_POINT	NUMBER		
);

CREATE TABLE tbl_users(
U_CODE	VARCHAR2(6)	NOT NULL	PRIMARY KEY,
U_NAME	nVARCHAR2(125)	NOT NULL	,
U_TEL	nVARCHAR2(125)		,
U_ADDR	nVARCHAR2(125)		
);

CREATE TABLE tbl_books(
B_CODE	VARCHAR2(6)	NOT NULL	PRIMARY KEY,
B_NAME	nVARCHAR2(125)	NOT NULL	,
B_AUTHER	nVARCHAR2(125)	NOT NULL	,
B_COMP	nVARCHAR2(125)		,
B_YEAR	NUMBER	NOT NULL	,
B_IPRICE	NUMBER		,
B_RPRICE	NUMBER	NOT NULL	
);

ALTER TABLE tbl_rent_book -- 연동되는 테이블
ADD CONSTRAINT FK_book
FOREIGN KEY(rent_bcode) -- PK키와 연동되는 테이블의 컬럼
REFERENCES tbl_books(b_code); -- PK키로 설정된 것. n:1에서 1 쪽의 컬럼

ALTER TABLE tbl_rent_book -- 연동되는 테이블
ADD CONSTRAINT FK_USER
FOREIGN KEY(rent_ucode) -- PK키와 연동되는 테이블의 컬럼
REFERENCES tbl_users(u_code); -- PK키로 설정된 것. n:1에서 1 쪽의 컬럼

SELECT * FROM tbl_books
ORDER BY b_code;

SELECT * FROM tbl_users
WHERE u_name LIKE '%' || '김' || '%';

SELECT * FROM tbl_rent_book;

CREATE SEQUENCE SEQ
START WITH 1 INCREMENT BY 1;